### ISSUE TITLE
Server Side? Client Side?

### ISSUE THREAD

**Issue by cootshk** [George-lewis/AutoSmelt#1]
Just wondering if this is needed on client AND server side or JUST server side.

**Comment by George-lewis** [comment]
Hi cootshk! I haven't actually tested it with a dedicated server so you'd have to try, or I can test it later.

Which version of MC are you using? Let me know and I'll generate a new Jar file. Thanks.

**Comment by cootshk** [comment]
I am using 1.17.1 on a fabric server with modded pickaxes and ores as well as normal ones.

**Comment by George-lewis** [comment]
Hi again. I've done some research and updated a few things. I have released version 2 of Autosmelt, which you can find here: https://github.com/George-lewis/AutoSmelt/releases/tag/v2.0.0

It turns out there was a problem with how my mod was set up, and it was never going to work with a dedicated server. Version 2 fixes this, and also updates the mod to target Minecraft 1.17.x, among other things. Also, I have changed the way the mod works slightly: You now need the correct tool for the smelting to work (e.g. a pickaxe with the enchantment will no longer smelt sand into glass).

As for client side / server side, you will need to install it on both.

By the way, the mod is expecting fabric loader `0.11.6`, and fabric api `0.40.0+1.17`, so please ensure those are up to date.

~~Finally, I found out that the video on the readme is dead, so here's a new one I just quickly recorded: https://streamable.com/ktsn6x~~

Check out the new video in the readme!

Please let me know if that works for you

**Comment by cootshk** [comment]
Thanks!
